In [1]:
import numpy as np
import pandas as pd

def generate(size, dimension, seed):
    n = size
    d = dimension
    
    B = np.random.randint(-3, 3, (d, d))
    
    # Designate causal order. In this case, 0, 1, 2, ..., d to make it simpler
    B[0,:] = 0 # x_0 is a parant of all variables including indirect parent.
    for i in range(1, d):
        for j in range(i, d):
            B[i, j] = 0
    B = B.T
    
    print("Ground Truth:")
    print(B)
    
    cols = []
    for i in range(d):
        cols.append("x_" + str(i))
    
    df = pd.DataFrame(columns=cols)
    
    for _ in range(n):
        dataset = [0 for _ in range(d)]
        dataset[0] = float(np.random.uniform(size=1))
        for i in range(1, d):
            for j in range(i):
                dataset[i] = B[j, i] * dataset[j] + float(np.random.uniform(size=1))
        df = df.append(pd.Series(dataset, index=df.columns), ignore_index = True)
        
    directlingam_result = []
    notears_result = []
    num_nodes = len(B)
    num_edges = num_nodes
    edge_coefficient_range = [0.5, 2.0]
    return df, B

In [2]:
generate(10, 14, 3)

Ground Truth:
[[ 0 -1 -1  2 -3  1 -1 -1 -3 -3  1 -3  1  1]
 [ 0  0  1  2  2 -1  2 -3  1  0 -2 -3 -1 -2]
 [ 0  0  0  2  2  2  0 -3 -2  1  0 -2  1  0]
 [ 0  0  0  0 -1  1  2  0  1 -3 -2  2 -3 -2]
 [ 0  0  0  0  0 -2  1 -2 -3 -1 -3  0 -1  1]
 [ 0  0  0  0  0  0 -2 -2 -1  2 -1 -3  0  1]
 [ 0  0  0  0  0  0  0 -1  2 -2 -1 -3 -1  2]
 [ 0  0  0  0  0  0  0  0  0  2  2  1 -1 -3]
 [ 0  0  0  0  0  0  0  0  0 -3  2 -1 -2  1]
 [ 0  0  0  0  0  0  0  0  0  0 -2 -3  1  2]
 [ 0  0  0  0  0  0  0  0  0  0  0 -3  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1 -2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


(        x_0       x_1       x_2       x_3       x_4       x_5        x_6  \
 0  0.846814  0.062674  0.292182  1.350134 -0.765233  2.163373  -3.347012   
 1  0.187451  0.334646  0.789921  2.379330 -2.349351  5.693405 -11.034434   
 2  0.219310 -0.048210  0.860902  1.852406 -1.347814  2.981595  -5.461086   
 3  0.205239 -0.182082  0.067245  0.522572  0.167885  0.348799  -0.228791   
 4  0.241003  0.716297  0.905571  2.727289 -2.046465  4.471280  -8.895602   
 5  0.356467 -0.328278 -0.264981 -0.520640  1.039198 -1.500049   3.285597   
 6  0.110113 -0.010477  0.243005  1.397265 -1.120702  2.958253  -5.406181   
 7  0.120868 -0.001435  0.368992  1.653499 -1.247488  2.892473  -4.978365   
 8  0.610250 -0.432166  0.206213  0.789783 -0.451846  0.943305  -1.245148   
 9  0.779905 -0.135886  0.217052  1.200734 -0.224072  0.841351  -1.130804   
 
          x_7       x_8       x_9      x_10       x_11       x_12      x_13  
 0   3.891457  0.847536 -2.324732  4.837955 -13.551840 -12.582386  0.8021