## とりあえず動くかどうか試すところ

In [1]:
import sys, os
import numpy as np
import pandas as pd

sys.path.append(os.path.join('..'))
import original_lingam

sys.path.append(os.path.join('..', 'sythetic_data'))
import generate
from generate import generate

sys.path.append(os.path.join('..', 'related_methods'))
import notears

sys.path.append(os.path.join('..', 'related_methods'))
import ges

sys.path.append(os.path.join('..', 'original_lingam'))
from original_lingam.utils import make_dot

import scipy
import networkx
import seaborn as sns
import matplotlib.pyplot as plt
import sempler_tool
import criteria

np.set_printoptions(precision=3, suppress=True)
np.random.seed(2022)

C:\Users\USER\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [4]:
model = original_lingam.DirectLiNGAM("pwling")
model.fit(generate(1000, 3)[0])
print(model.causal_order_)

acyclic_W = notears.utils.threshold_output(model.adjacency_matrix_)
# correct = notears_tool.utils.threshold_output(m)
# directlingam_result.append(SHD(acyclic_W, correct))
# directlingam_result

Ground Truth:
[[ 0  0  0]
 [-3  0  0]
 [-3 -3  0]]
<class 'pandas.core.frame.DataFrame'>
          x_0       x_1       x_2
0    0.486988 -0.563307  2.586884
1    0.721135 -1.332051  4.829734
2    0.957044 -2.503089  7.848775
3    0.619429 -0.880758  3.386481
4    0.292499 -0.578823  1.755133
..        ...       ...       ...
995  0.324276 -0.180326  1.323664
996  0.173584 -0.443961  1.830311
997  0.457946 -0.611786  2.672669
998  0.159587 -0.177919  1.383686
999  0.675787 -1.265009  4.711774

[1000 rows x 3 columns]
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
entropy
[0, 1, 2]


C:\Users\USER\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:138: FutureWarning: The default of 'normalize' will be set to False in version 1.2 and deprecated in version 1.4.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LassoLarsIC())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples). 
  FutureWarning,
C:\Users\USER\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:138: FutureWarning: The default of 'normalize' will be set to False in version 1.2 and deprecated in version 1.4.
If you wish to scale the data, use Pipeline with a StandardScaler in a preproc

In [6]:
acyclic_W

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [7]:
correct = notears.utils.threshold_output(generate(1000, 3)[1])
correct

Ground Truth:
[[ 0  0  0]
 [-3  0  0]
 [-3 -3  0]]


array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [9]:
correct = notears.utils.threshold_output(generate(1000, 3)[1])
print(criteria.SHD(acyclic_W, correct))

Ground Truth:
[[ 0  0  0]
 [-3  0  0]
 [-3 -3  0]]
1.0


In [49]:
acyclic_W = notears.utils.threshold_output(model.adjacency_matrix_)

In [5]:
correct = notears.utils.threshold_output(generate(1000, 3)[1])
correct

Ground Truth:
[[ 0  0  0]
 [-3  0  0]
 [-3 -3  0]]


array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [51]:
correct = notears.utils.threshold_output(generate(1000, 3)[1])
print(SHD(acyclic_W, correct))

Ground Truth:
[[ 0  0  0]
 [-1  0  0]
 [ 0 -1  0]]


KeyError: 1

In [50]:
acyclic_W

array([[0., 0., 0.],
       [1., 0., 1.],
       [1., 0., 0.]])

In [2]:

generate(1000, 3)

Ground Truth:
[[ 0  0  0]
 [-3  0  0]
 [-3 -3  0]]


(          x_0       x_1       x_2
 0    0.486988 -0.563307  2.586884
 1    0.721135 -1.332051  4.829734
 2    0.957044 -2.503089  7.848775
 3    0.619429 -0.880758  3.386481
 4    0.292499 -0.578823  1.755133
 ..        ...       ...       ...
 995  0.324276 -0.180326  1.323664
 996  0.173584 -0.443961  1.830311
 997  0.457946 -0.611786  2.672669
 998  0.159587 -0.177919  1.383686
 999  0.675787 -1.265009  4.711774
 
 [1000 rows x 3 columns], array([[ 0,  0,  0],
        [-3,  0,  0],
        [-3, -3,  0]]))

In [6]:
generate(1000, 3)[0]

Ground Truth:
[[ 0  0  0]
 [-3  0  0]
 [-3 -3  0]]


x_0       x_1       x_2
0    0.486988 -0.563307  2.586884
1    0.721135 -1.332051  4.829734
2    0.957044 -2.503089  7.848775
3    0.619429 -0.880758  3.386481
4    0.292499 -0.578823  1.755133
..        ...       ...       ...
995  0.324276 -0.180326  1.323664
996  0.173584 -0.443961  1.830311
997  0.457946 -0.611786  2.672669
998  0.159587 -0.177919  1.383686
999  0.675787 -1.265009  4.711774

[1000 rows x 3 columns]

# NO TEARS_TEST

In [2]:
data = generate(10, 2)[0]
output_dict = notears.run(notears.notears_standard, data, notears.loss.least_squares_loss, notears.loss.least_squares_loss_grad, e=1e-8, verbose=False)
acyclic_W = notears.utils.threshold_output(output_dict[0]['W'])
print(criteria.SHD(notears.utils.threshold_output(generate(10, 2)[1]), acyclic_W))

Ground Truth:
[[0 0]
 [2 0]]
Ground Truth:
[[0 0]
 [2 0]]
2.0


# GES_TEST

In [5]:
data = np.array(generate(10, 2)[0])
estimate, score = ges.fit_bic(data)
print(criteria.SHD(notears.utils.threshold_output(generate(10, 2)[1]), estimate))

Ground Truth:
[[0 0]
 [2 0]]
Ground Truth:
[[0 0]
 [2 0]]
1.0


In [ ]:
# import ../algorithms

# x = generate(1000,2) #designate n and d

# lingam = LINGAM(kernel)
# new_lingam = NEW_LINAGM()
# notears
# GDS


# lingam.fit(x)
# new_lingam.fit(x)

In [32]:
print(sys.path.append(os.path.join('..', 'related_methods')))

None


In [31]:
import sys, os

sys.path.append(os.path.join('..', 'sythetic_data'))

import generate
from generate import generate

Ground Truth:
[[0 0]
 [0 0]]


x_0       x_1
0   0.962632  0.715997
1   0.369121  0.402988
2   0.005790  0.713744
3   0.559139  0.605746
4   0.023637  0.708893
..       ...       ...
95  0.030190  0.600448
96  0.531652  0.337501
97  0.848442  0.705007
98  0.748830  0.210626
99  0.777658  0.825893

[100 rows x 2 columns]

In [ ]:
C:\Users\USER\thesis